services:
  - type: static
    name: watchlog-fe
    buildCommand: corepack enable pnpm && pnpm install && pnpm build
    staticPublishPath: dist
    env:
      - key: NODE_VERSION
        value: 20
    startCommand: pnpm preview -- --host 0.0.0.0 --port $PORT

